apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: quant-generator
    image: localhost:5000/rand-num-image
    volumeMounts:
    - name: shared-data
      mountPath: /app
