apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: qdeploy
  name: qdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qdeploy
spec:
  containers:
  - args:
    - i=0; while i=$((i+1)); do echo Hello from Class $i; sleep 5; done
    command:
    - /bin/bash
    - -c
    - --
    image: nginx:latest
    imagePullPolicy: Always
    name: get-num-pod
status: {}
