apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: quantum-number1
  name: quantum-number1
spec:
  containers:
  - image: localhost:5000/rand-num-image
    name: quantum-number1
    ports:
    - containerPort: 5701
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
