apiVersion: v1
kind: Pod
metadata:
  name: credit-card
spec:
  shareProcessNamespace: true
  containers:
  - image: localhost:5000/rand-num-image
    name: quant-num
  - image: nginx:lateest
    name: shell
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 100;echo 'tamilhce testing the shared_pipe'; done"]
  